# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
        uri-encoding: UTF-8
    port: 8080

# mysql
spring:
    datasource:
#        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://172.19.20.5:3306/zhangchi?serverTimezone=UTC&useSSL=false
        username: zhangchi
        password: 123456
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

