# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
        uri-encoding: UTF-8
    port: 8080

# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://rm-2ze5y2680283kde34.mysql.rds.aliyuncs.com/shebao_dispatch?
        username: p_dispatch_ws
        password: Gp1-Lf1!Gr
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

